name: Run ESLint
on: [push, pull_request]
jobs:
  eslint-check:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.1.0
    - name: Install eslint
      run: npm i -g eslint
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
