name: Run ESLint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@1.1.5
      with:
        context: ESLint
        token: ${{ secrets.GITHUB_TOKEN }}
        status: pending
    - name: Install eslint
      run: npm i -g eslint
    - name: Install modules
      run: npm i
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
    - name: Set final commit status
      uses: myrotvorets/set-commit-status-action@1.1.5
      if: always()
      with:
        context: ESLint
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
